# Nome da aplicação
spring.application.name=RegistrationSystem

server.port=8080

# CONFIGURAÇÃO DO BANCO H2
# mem:testdb ? banco em memória (some quando a aplicação reinicia)
# DB_CLOSE_DELAY=-1 ? mantém o banco vivo mesmo sem conexão ativa
# DB_CLOSE_ON_EXIT=FALSE ? não fecha automaticamente ao encerrar
spring.datasource.url=${DATABASE_URL}

# Driver do banco H2
spring.datasource.driver-class-name=org.h2.Driver

# Usuário do banco
spring.datasource.username=${DATABASE_USERNAME}

# Senha do banco
spring.datasource.password=${DATABASE_PASSWORD}

# CONFIGURAÇÃO DO JPA / HIBERNATE
# Define qual banco o Hibernate está usando (H2)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# update ? cria/atualiza tabelas automaticamente baseado nas entidades
# (não apaga dados existentes)
spring.jpa.hibernate.ddl-auto=update

# Mostra os SQLs no console
spring.jpa.show-sql=true

# H2 CONSOLE (INTERFACE WEB)
# Habilita o console web do H2
spring.h2.console.enabled=true

# Caminho para acessar no navegador
# http://localhost:8080/h2-console
spring.h2.console.path=/h2-console
